### ISSUE TITLE
Same Title Permuting Tabs

### ISSUE THREAD

**Issue by benjic** [glesica/pseudo-pins#5]
If there are multiple tabs with the same title in a group they may change position in response to a title change in another tab. This behavior was observed on a Mac OS X El Capitan. I cannot replicate it on Linux 49.0.2623.87 (Developer Build) (64-bit).
## Steps to Reproduce
- Open a document page that matches a group pattern
- Open another instance of the page
- Open an third page that does not belong to the group
- Run the following script in the console of the third tab to ensure it's title changes periodically
  - `setInterval(() => document.title = new Date().getTime(), 1000)`

**Comment by glesica** [comment]
I have a PR up that I think should fix this. I don't have a Mac around at the moment, I'll try to test it tomorrow.
